### ISSUE TITLE
missing zero3 install/calibrate/test

### ISSUE THREAD

**Issue by twdragon** [RoverRobotics/rover_tools#19]
We are trying to do our very first test of a Zero3. Using the available zero2_* doesn't work. 
Are there any updates for zero3? Thanks in advance!

**Comment by RoverRoboticsProduction** [comment]
Right now the test is not functional within Rover Tools, but the test in question was only for basic troubleshooting and verification that the robot could move as expected. You can replicate the test using the PS4 controller or via commands, it is a simple test involving turning and driving straight.
