### ISSUE TITLE
Git status error

### ISSUE THREAD

**Issue by shoemakerlevy9** [RoverRobotics/rover_tools#5]
After using the install script, the github repos report an error when running the command git status. This makes it hard to tell which version of the driver you are using which is really bad for support tickets.

![image](https://user-images.githubusercontent.com/6597441/124310978-fb8f7100-db3a-11eb-8d10-c95abf701b4e.png)

**Comment by drhieu** [comment]
Check your tag; NOT BRANCH. IT SHOULD NOT BE IN ANY BRANCH

**Comment by shoemakerlevy9** [comment]
git describe --tags
