### ISSUE TITLE
Multiple menu items have version number hardcoded 

### ISSUE THREAD

**Issue by shoemakerlevy9** [RoverRobotics/rover_tools#6]
Hard coding the version number makes it likely that it won't be updated and will report the wrong value
![image](https://user-images.githubusercontent.com/6597441/124311216-6476e900-db3b-11eb-85a2-60fd08851a16.png)
![image](https://user-images.githubusercontent.com/6597441/124311271-79537c80-db3b-11eb-86e7-b6d788f264ad.png)

**Comment by jbrover** [comment]
They aren't hard-coded and this issue isn't a real issue. See tool_versions.json
