### ISSUE TITLE
Openssh removed after failed install

### ISSUE THREAD

**Issue by shoemakerlevy9** [RoverRobotics/rover_tools#9]
After running the install on an RPi and having it fail to install DS4 the RPI was left in a state without openssh server. If you then lose connection (which happened to me several times) you then can't ssh back in.

**Comment by drhieu** [comment]
Can you explain this more. How does the RPi stuck in a stage without openssh server? Did your RpI ssh timeout? Is the SSH server still running if you connect directly to the Rpi with a monitor ?
